version: '3.1'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: betting
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - hibet-postgres:/var/lib/postgresql/data/
    ports:
      - 5432:5432

volumes:
  hibet-postgres:
