name: Build Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      REPO: docker.hq-hydra.hibyte.ro/hibyte # REMEMBER TO CHANGE IF COPY PASTING THIS
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Extract tag from GITHUB_REF
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Set up Java
        uses: actions/setup-java@v2
        with: # running setup-java again overwrites the settings.xml
          distribution: 'adopt'
          java-version: '17'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.6.2

      - name: Set up Settings.xml
        run: |
          echo "$SETTINGS_XML" > ./settings.xml
        shell: bash
        env:
          SETTINGS_XML: ${{ secrets.SETTINGS_XML }}

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Extract Tag Name
        id: extract_tag
        run: echo "##[set-output name=tag;]$(echo ${GITHUB_REF#refs/tags/})"

      - name: test
        run: echo ${{ secrets.HIBYTE_NEXUS_USER }}


      - name: Test and build
        run: mvn clean install -DskipTests

      - name: Login to Docker Hub
        run: docker login docker.hq-hydra.hibyte.ro -u ${{ secrets.HIBYTE_NEXUS_USER }} -p ${{ secrets.HIBYTE_NEXUS_PASSWORD }} # same credentials :D

      - name: Build Docker Image
        run: docker build -t hibet-be .

      - name: Tag and Push Docker Images
        run: |
          version_tag=$(echo "${{ env.VERSION }}" | awk -F'/' '{print $2}')
          image_name=hibet-be
          docker tag $image_name:latest $REPO/$image_name:$version_tag
          docker push $REPO/$image_name:$version_tag
